# 警告与错误

- 能被程序自主处理的异常为 `WARNING` , 不能的为 `ERROR` .  
- 凡是可能在构造过程中出现 `ERROR` 的类, 都应将可能出现 `ERROR` 的代码块移动到类的 `Init()` 函数中.  
- 在 `Init()` 方法调用过程中, 若出现 `ERROR` , 立即终止初始化, 回收开辟的内存空间并返回 `ERROR` 的数字代码.  
- 在程序运行过程中, 若出现 `WARNING` , 由程序自主处理.  
- 若存在用于记录 `ERROR` 的类, 应在调用链的最上层记录出现的 `ERROR` .  
- 若存在用于记录 `WARNING` 的类, 应在 `WARNING` 出现时记录.  
- 在程序初始化末尾, 若在初始化的过程中存在 `WARNING` , 汇总所有 `WARNING` 的信息并输出到屏幕, 由用户自己决定是否继续运行.  
- 对于以前存在返回值且可能出现 `ERROR` 的函数, 将返回的对象以指针或引用的形式传入, 返回值改为 `ERROR` 代码.  
- 关于 `ERROR` 代码:
  - `0` 表示成功执行.  
  - 正数代表全局 `ERROR` 码.  
  - 负数代表临时 `ERROR` 码, 指仅可能在此函数中出现的 `ERROR` , 由函数自行定义.  